export const Users = [
  {
    id: 1,
    profilePicture: "./assets/person/1.jpeg",
    username: "baba jide",
  },
  {
    id: 2,
    profilePicture: "./assets/person/2.jpeg",
    username: "kilo kan",
  },
  {
    id: 3,
    profilePicture: "./assets/person/3.jpeg",
    username: "saro anikulapo",
  },
  {
    id: 4,
    profilePicture: "./assets/person/4.jpeg",
    username: "enugbon",
  },
  {
    id: 5,
    profilePicture: "./assets/person/5.jpeg",
    username: "survival remorse",
  },
  {
    id: 6,
    profilePicture: "./assets/person/6.jpeg",
    username: "aurora",
  },
  {
    id: 7,
    profilePicture: "./assets/person/7.jpeg",
    username: "love",
  },
  {
    id: 8,
    profilePicture: "./assets/person/8.jpeg",
    username: "water",
  },
  {
    id: 9,
    profilePicture: "./assets/person/9.jpeg",
    username: "man lay",
  },
  {
    id: 10,
    profilePicture: "./assets/person/10.jpeg",
    username: "closed off",
  },
];


export const Posts = [
    {
        id:1,
        desc:"i don't know what you know",
        photo:"./assets/post/1.jpeg",
        date: "5 mins ago",
        userId:1,
        like:32,
        comment:9,
    },
    {
        id:2,
        desc:"wheels",
        photo:"./assets/post/2.jpeg",
        date: "50 mins ago",
        userId:2,
        like:32,
        comment:9,
    },
    {
        id:3,
        desc:"no regrets",
        photo:"./assets/post/3.jpeg",
        date: "59 mins ago",
        userId:3,
        like:32,
        comment:9,
    },
    {
        id:4,
        desc:"nananana",
        photo:"./assets/post/4.jpeg",
        date: "7 mins ago",
        userId:4,
        like:32,
        comment:9,
    },
    {
        id:5,
        desc:"flattery",
        photo:"./assets/post/5.jpeg",
        date: "8 mins ago",
        userId:5,
        like:32,
        comment:9,
    },
    {
        id:6,
        desc:"grace",
        photo:"./assets/post/6.jpeg",
        date: "55 mins ago",
        userId:6,
        like:32,
        comment:9,
    },
    {
        id:7,
        desc:"october 20 10 10",
        photo:"./assets/post/7.jpeg",
        date: "5 mins ago",
        userId:7,
        like:32,
        comment:9,
    },
    {
        id:8,
        desc:"perfect",
        photo:"./assets/post/8.jpeg",
        date: "5 mins ago",
        userId:8,
        like:32,
        comment:9,
    },
    {
        id:9,
        desc:"lol",
        photo:"./assets/post/9.jpeg",
        date: "58 mins ago",
        userId:9,
        like:32,
        comment:9,
    },
    {
        id:10,
        desc:"have your way",
        photo:"./assets/post/10.jpeg",
        date: "25 mins ago",
        userId:10,
        like:32,
        comment:9,
    }
]